name: Test suite

on:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  tests:
    name: Meteor ${{ matrix.meteor }} tests
    runs-on: ubuntu-latest
    steps:

      # CHECKOUTS
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout leaonline:testing repo
        uses: actions/checkout@v4
        with:
          repository: leaonline/testing
          path: github/testing

      - name: Checkout leaonline:utils repo
        uses: actions/checkout@v4
        with:
          repository: leaonline/utils
          path: github/utils

      - name: Checkout leaonline:theme repo
        uses: actions/checkout@v4
        with:
          repository: leaonline/theme
          path: github/theme

      # CACHING
      - name: Install Meteor
        id: cache-meteor-install
        uses: actions/cache@v4
        with:
          path: ~/.meteor
          key: v1-meteor-${{ hashFiles('.meteor/versions') }}
          restore-keys: |
                v1-meteor-

      - name: Cache NPM dependencies
        id: cache-meteor-npm
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: v1-npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
                v1-npm-

      - name: Cache Meteor build
        id: cache-meteor-build
        uses: actions/cache@v4
        with:
          path: |
            .meteor/local/resolver-result-cache.json
            .meteor/local/plugin-cache
            .meteor/local/isopacks
            .meteor/local/bundler-cache/scanner
          key: v1-meteor_build_cache-${{ github.ref }}-${{ github.sha }}
          restore-key: |
            v1-meteor_build_cache-

      - name: Setup meteor
        uses: meteorengineer/setup-meteor@v1
        with:
          meteor-release: '3.0.2'

      - name: Install NPM Dependencies
        run: meteor npm install

      - name: Run Tests
        run: sh ./test.sh -c -o

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-folder
          path: .coverage/

  coverage:
    name: Coverage report
    runs-on: ubuntu-latest
    needs: [tests]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download coverage
        uses: actions/download-artifact@v4
        with:
          name: coverage-folder
          path: .coverage/


      - name: Coverage Report
        uses: VeryGoodOpenSource/very_good_coverage@v2
        with:
          path: ".coverage/lcov.info"
          min_coverage: 90 # TODO increase to 95!
