name: Test suite

on:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:

  tests:
    name: Meteor ${{ matrix.meteor }} tests
    runs-on: ubuntu-latest
    steps:

      # CHECKOUTS
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout leaonline:testing repo
        uses: actions/checkout@v2
        with:
          repository: leaonline/testing
          path: leaonline-accounts/lib/testing

      - name: Checkout leaonline:theme repo
        uses: actions/checkout@v2
        with:
          repository: leaonline/theme
          path: leaonline-accounts/lib/theme

      # CACHING
      - name: Cache Meteor install
        id: cache-meteor-install
        uses: actions/cache@v2
        with:
          path: ~/.meteor
          key: v1-meteor-${{ hashFiles('.meteor/versions') }}

      - name: Cache NPM dependencies
        id: cache-meteor-npm
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: v1-npm-${{ hashFiles('package-lock.json') }}

      - name: Cache Meteor build
        id: cache-meteor-build
        uses: actions/cache@v2
        with:
          path: |
            .meteor/local/resolver-result-cache.json
            .meteor/local/plugin-cache
            .meteor/local/isopacks
            .meteor/local/bundler-cache/scanner
          key: v1-meteor_build_cache-${{ github.ref }}-${{ github.sha }}

      - name: Setup meteor
        uses: meteorengineer/setup-meteor@v1
        if: steps.cache-meteor-install.outputs.cache-hit != 'true'
        with:
          meteor-release: '2.1.1'

      - name: Install NPM Dependencies
        if: steps.cache-meteor-npm.outputs.cache-hit != 'true'
        run: meteor npm ci

      - name: Run Tests
        run: sh ./test.sh -cv

      - name: Coverage Report
        uses: romeovs/lcov-reporter-action@v0.2.21
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          lcov-file: ./coverage/lcov.info
